package main

import "time"

// CommandRequest encapsulates command execution parameters sent from the main service.
// All fields use json tags for HTTP API serialization.
type CommandRequest struct {
	// Command is the binary name to execute (e.g., "ffmpeg", "python")
	Command string `json:"command"`

	// Args are the command-line arguments to pass to the binary
	Args []string `json:"args"`

	// Env contains environment variables to set for the command execution
	// Key-value pairs like {"LOG_LEVEL": "info"}
	Env map[string]string `json:"env,omitempty"`

	// WorkingDir specifies the working directory for command execution
	// Must be within the shared volume path (e.g., "/data/meetings/xxx")
	WorkingDir string `json:"working_dir,omitempty"`

	// Timeout specifies the maximum execution time in seconds
	// If zero, the default timeout from commands.yaml will be used
	Timeout time.Duration `json:"timeout"`
}

// CommandResponse contains the result of command execution returned to the main service.
// All fields use json tags for HTTP API serialization.
type CommandResponse struct {
	// Success indicates whether the command execution was successful (exit_code == 0)
	Success bool `json:"success"`

	// ExitCode is the process exit code (0 for success, non-zero for errors)
	ExitCode int `json:"exit_code"`

	// Stdout contains the standard output captured from the command
	Stdout string `json:"stdout"`

	// Stderr contains the standard error captured from the command
	Stderr string `json:"stderr"`

	// DurationMs is the command execution duration in milliseconds
	DurationMs int64 `json:"duration_ms"`

	// OutputFiles lists the files generated by the command (e.g., converted audio files)
	// Currently not auto-detected, expected to be inferred by the caller
	OutputFiles []string `json:"output_files,omitempty"`
}

// Config represents the complete configuration loaded from commands.yaml.
// It defines command whitelists and security policies.
type Config struct {
	// Commands is the list of allowed commands with their configurations
	Commands []CommandConfig `yaml:"commands"`

	// Security contains global security policies
	Security SecurityConfig `yaml:"security"`
}

// CommandConfig defines the whitelist configuration for a specific command.
// Each command must be explicitly configured to be executable.
type CommandConfig struct {
	// Name is the command identifier (e.g., "ffmpeg", "python")
	Name string `yaml:"name"`

	// BinaryPath is the absolute path to the binary executable
	BinaryPath string `yaml:"binary_path"`

	// AllowedArgsPatterns are regex patterns that all arguments must match
	// Used to prevent command injection attacks
	AllowedArgsPatterns []string `yaml:"allowed_args_patterns"`

	// EnvWhitelist contains environment variable names that are allowed
	// Only these env vars can be passed from the request
	EnvWhitelist []string `yaml:"env_whitelist"`

	// Timeout is the default execution timeout (e.g., "300s", "10m")
	Timeout string `yaml:"timeout"`

	// MaxConcurrent is the maximum number of concurrent executions allowed
	MaxConcurrent int `yaml:"max_concurrent"`
}

// SecurityConfig defines global security policies for command execution.
// These policies apply to all commands and cannot be bypassed.
type SecurityConfig struct {
	// SharedVolumePath is the base path for the shared volume (e.g., "/data")
	// All file paths must be within this directory
	SharedVolumePath string `yaml:"shared_volume_path"`

	// ForbiddenPaths are directories that cannot be accessed (e.g., "/etc", "/sys")
	// Access attempts to these paths will be rejected
	ForbiddenPaths []string `yaml:"forbidden_paths"`

	// MaxCommandLength is the maximum allowed length of command + arguments
	// Used to prevent excessively long commands
	MaxCommandLength int `yaml:"max_command_length"`

	// EnableAuditLog enables or disables audit logging
	EnableAuditLog bool `yaml:"enable_audit_log"`

	// AuditLogPath is the file path for audit logs (e.g., "/var/log/cmd-executor-audit.log")
	AuditLogPath string `yaml:"audit_log_path"`
}
